### PR TITLE
support multi unicode chars

### PR DESCRIPTION
**Pull request by kounoike**
Japanese user needs encoding unicode string such as u"テスト".
but, currently only support single character at once.

This PR fix this problem.

### CODE REVIEW

**Comment by zerok** [comment]
Hi :-) Thank you for your pull request. Could you just please fix the line-length on line 17 so that the pep8-test passes with tox and rebase your pull-request afterwards? Thanks!

**Comment by kounoike** [comment]
hmm... sorry, I'm newbie for git. I don't know how to use git rebase.
what command to do rebase?
1. git checkout pr-morethan-onechar ???
2. ???
3. edit pyjavapropertiesu.py (fix line-length)
4. ???

**Comment by kounoike** [comment]
I'm confused in my branch.
I made new PR.

**Comment by zerok** [comment]
Ah ok :) Just in case you ever want to change the previous commit: Make your change and then run `git commit --amend`. This way you "open" a commit again, add your changes and then commit the result :)

**Pull request closed without merging**
